CREATE DATABASE demoshop;


USE demoshop; -- Chọn cơ sở dữ liệu
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

DBCC CHECKIDENT ('Manufacturers', RESEED, 0);
DBCC CHECKIDENT ('Users', RESEED, 0);
DBCC CHECKIDENT ('Cars', RESEED, 0);
DBCC CHECKIDENT ('CarModels', RESEED, 0);
DBCC CHECKIDENT ('Listings', RESEED, 0);
DBCC CHECKIDENT ('CarImages', RESEED, 0);
DBCC CHECKIDENT ('Favorites', RESEED, 0);


SELECT * FROM Manufacturers;

SELECT * FROM CarModels;

SELECT * FROM Users;

SELECT * FROM Cars;

SELECT * FROM Listings;

SELECT * FROM CarImages;

SELECT * FROM Favorites;