/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Xóa dữ liệu cũ trước khi thêm mới
  await knex('Favorites').del();
  await knex('Listings').del();
  await knex('CarImages').del();
  await knex('Cars').del();
  await knex('CarModels').del();
  await knex('Manufacturers').del();
  await knex('Users').del();

  // Thêm dữ liệu vào bảng Users
  await knex('Users').insert([
      { Username: 'lebao', Password: '123', FullName: 'Lê Bảo', Phone: '1234567890', Email: 'bao@example.com', Address: '123 Elm Street' },
      { Username: 'hihi', Password: '2004', FullName: 'Jane Doe', Phone: '0987654321', Email: 'jane@example.com', Address: '456 Oak Street' },
  ]);

  // Thêm dữ liệu vào bảng Manufacturers
  await knex('Manufacturers').insert([
      { ManufacturerName: 'Toyota' },
      { ManufacturerName: 'Volkswagen' },
      { ManufacturerName: 'Ford' },
      { ManufacturerName: 'Chevrolet' },
      { ManufacturerName: 'Nissan' },
      { ManufacturerName: 'Hyundai' },
      { ManufacturerName: 'KIA' },
      { ManufacturerName: 'Subaru' },
      { ManufacturerName: 'Mercedes' },
      { ManufacturerName: 'BMW' },
      { ManufacturerName: 'Lexus' },
      { ManufacturerName: 'Porsche' },
      { ManufacturerName: 'VinFast' },
      { ManufacturerName: 'Mazda' },
      { ManufacturerName: 'Honda' },
      { ManufacturerName: 'Audi' }
  ]);

  // Thêm dữ liệu vào bảng CarModels
  await knex('CarModels').insert([
      { ManufacturerID: 1, ModelName: 'Vios' },
      { ManufacturerID: 1, ModelName: 'Innova' },
      { ManufacturerID: 1, ModelName: 'Fortuner' },
      { ManufacturerID: 1, ModelName: 'Camry' },
      { ManufacturerID: 1, ModelName: 'Corolla Altis' },
      { ManufacturerID: 1, ModelName: 'Corolla Cross' },
      { ManufacturerID: 1, ModelName: 'Yaris' },
      { ManufacturerID: 1, ModelName: 'Wigo' },
      { ManufacturerID: 2, ModelName: 'Tiguan' },
      { ManufacturerID: 2, ModelName: 'Polo' },
      { ManufacturerID: 2, ModelName: 'Teramont' },
      { ManufacturerID: 2, ModelName: 'Touareg' },
      { ManufacturerID: 2, ModelName: 'T-Cross' },
      { ManufacturerID: 2, ModelName: 'Beetle' },
      { ManufacturerID: 2, ModelName: 'Amarok' },
      { ManufacturerID: 2, ModelName: 'Atlas' },
      { ManufacturerID: 3, ModelName: 'Ranger' },
      { ManufacturerID: 3, ModelName: 'Everest' },
      { ManufacturerID: 3, ModelName: 'EcoSport' },
      { ManufacturerID: 3, ModelName: 'Territory' },
      { ManufacturerID: 3, ModelName: 'Explorer' },
      { ManufacturerID: 3, ModelName: 'F-150' },
      { ManufacturerID: 3, ModelName: 'Transit' },
      { ManufacturerID: 3, ModelName: 'Focus' },
      { ManufacturerID: 4, ModelName: 'Alero' },
      { ManufacturerID: 4, ModelName: 'Astro' },
      { ManufacturerID: 4, ModelName: 'Avanlanche' },
      { ManufacturerID: 4, ModelName: 'Aveo' },
      { ManufacturerID: 4, ModelName: 'Beretta' },
      { ManufacturerID: 4, ModelName: 'Blazer' },
      { ManufacturerID: 4, ModelName: 'Bolt' },
      { ManufacturerID: 4, ModelName: 'Camaro' },
      { ManufacturerID: 5, ModelName: 'Navara' },
      { ManufacturerID: 5, ModelName: 'Sunny' },
      { ManufacturerID: 5, ModelName: 'Almera' },
      { ManufacturerID: 5, ModelName: 'X trail' },
      { ManufacturerID: 5, ModelName: 'Terra' },
      { ManufacturerID: 5, ModelName: 'Teana' },
      { ManufacturerID: 5, ModelName: '100NX' },
      { ManufacturerID: 5, ModelName: '200SX' },
      { ManufacturerID: 6, ModelName: 'Accent' },
      { ManufacturerID: 6, ModelName: 'Avante' },
      { ManufacturerID: 6, ModelName: 'Creta' },
      { ManufacturerID: 6, ModelName: 'Elantra' },
      { ManufacturerID: 6, ModelName: 'Getz' },
      { ManufacturerID: 6, ModelName: 'Grand i10' },
      { ManufacturerID: 6, ModelName: 'i20' },
      { ManufacturerID: 6, ModelName: 'Kona' },
      { ManufacturerID: 7, ModelName: 'Morning' },
      { ManufacturerID: 7, ModelName: 'Cerato' },
      { ManufacturerID: 7, ModelName: 'Sorento' },
      { ManufacturerID: 7, ModelName: 'K3' },
      { ManufacturerID: 7, ModelName: 'Sendona' },
      { ManufacturerID: 7, ModelName: 'Seltos' },
      { ManufacturerID: 7, ModelName: 'Carnival' },
      { ManufacturerID: 7, ModelName: 'Soluto' },
      { ManufacturerID: 8, ModelName: 'Ascent' },
      { ManufacturerID: 8, ModelName: 'BRZ' },
      { ManufacturerID: 8, ModelName: 'Crosstrek' },
      { ManufacturerID: 8, ModelName: 'Forester' },
      { ManufacturerID: 8, ModelName: 'Impreza' },
      { ManufacturerID: 8, ModelName: 'Legacy' },
      { ManufacturerID: 8, ModelName: 'Levorg' },
      { ManufacturerID: 8, ModelName: 'Outback' },
      { ManufacturerID: 9, ModelName: 'C-class' },
      { ManufacturerID: 9, ModelName: 'E-class' },
      { ManufacturerID: 9, ModelName: 'S-class' },
      { ManufacturerID: 9, ModelName: 'V-class' },
      { ManufacturerID: 9, ModelName: 'GLA' },
      { ManufacturerID: 9, ModelName: 'GLB' },
      { ManufacturerID: 9, ModelName: 'GLC' },
      { ManufacturerID: 9, ModelName: 'GLE' },
      { ManufacturerID: 10, ModelName: '3-Series' },
      { ManufacturerID: 10, ModelName: '4-Series' },
      { ManufacturerID: 10, ModelName: '5-Series' },
      { ManufacturerID: 10, ModelName: '7-Series' },
      { ManufacturerID: 10, ModelName: 'X3' },
      { ManufacturerID: 10, ModelName: 'X5' },
      { ManufacturerID: 10, ModelName: 'X7' },
      { ManufacturerID: 10, ModelName: 'X6' },
      { ManufacturerID: 11, ModelName: 'RX' },
      { ManufacturerID: 11, ModelName: 'LX' },
      { ManufacturerID: 11, ModelName: 'GX' },
      { ManufacturerID: 11, ModelName: 'FordCT 200' },
      { ManufacturerID: 11, ModelName: 'ES' },
      { ManufacturerID: 11, ModelName: 'ES 250' },
      { ManufacturerID: 11, ModelName: 'ES 300h' },
      { ManufacturerID: 11, ModelName: 'ES 350' },
      { ManufacturerID: 12, ModelName: '718' },
      { ManufacturerID: 12, ModelName: 'Macan' },
      { ManufacturerID: 12, ModelName: 'Panamera' },
      { ManufacturerID: 12, ModelName: '911' },
      { ManufacturerID: 12, ModelName: 'Cayenne' },
      { ManufacturerID: 12, ModelName: 'Taycan' },
      { ManufacturerID: 12, ModelName: '930' },
      { ManufacturerID: 12, ModelName: 'Boxster' },
      { ManufacturerID: 13, ModelName: 'LUX A2.0' },
      { ManufacturerID: 13, ModelName: 'LUX SA2.0' },
      { ManufacturerID: 13, ModelName: 'Fadil' },
      { ManufacturerID: 13, ModelName: 'VF e34' },
      { ManufacturerID: 13, ModelName: 'VF8' },
      { ManufacturerID: 13, ModelName: 'VF9' },
      { ManufacturerID: 13, ModelName: 'SA' },
      { ManufacturerID: 13, ModelName: 'VF 3' },
      { ManufacturerID: 14, ModelName: '3' },
      { ManufacturerID: 14, ModelName: 'CX-5' },
      { ManufacturerID: 14, ModelName: '6' },
      { ManufacturerID: 14, ModelName: '2' },
      { ManufacturerID: 14, ModelName: 'BT-50' },
      { ManufacturerID: 14, ModelName: 'CX-8' },
      { ManufacturerID: 14, ModelName: 'CX-3' },
      { ManufacturerID: 14, ModelName: 'CX-30' },
      { ManufacturerID: 15, ModelName: 'City' },
      { ManufacturerID: 15, ModelName: 'Civic' },
      { ManufacturerID: 15, ModelName: 'CR-V' },
      { ManufacturerID: 15, ModelName: 'Accord' },
      { ManufacturerID: 15, ModelName: 'Brio' },
      { ManufacturerID: 15, ModelName: 'HR-V' },
      { ManufacturerID: 15, ModelName: 'Jazz' },
      { ManufacturerID: 15, ModelName: 'Odyssey' },
      { ManufacturerID: 16, ModelName: 'A4' },
      { ManufacturerID: 16, ModelName: 'A5' },
      { ManufacturerID: 16, ModelName: 'Q5' },
      { ManufacturerID: 16, ModelName: 'A6' },
      { ManufacturerID: 16, ModelName: 'A8' },
      { ManufacturerID: 16, ModelName: 'Q7' },
      { ManufacturerID: 16, ModelName: '100' },
      { ManufacturerID: 16, ModelName: '200' }
  ]);

  // Thêm dữ liệu vào bảng Cars
  await knex('Cars').insert([
      { ModelID: 1, Year: 2022, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 75000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 450000000 },
      { ModelID: 2, Year: 2019, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 25000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 699000000 },
      { ModelID: 3, Year: 2015, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 107000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 488000000 },
      { ModelID: 4, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 38000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 695000000 },
      { ModelID: 5, Year: 2012, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 120, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 335000000 },
      { ModelID: 6, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 64000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 695000000 },
      { ModelID: 7, Year: 2017, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 60000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 414000000 },
      { ModelID: 8, Year: 2020, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 70000, Gear: 'Số sàn', FuelType: 'Máy xăng', Price: 235000000 },
      { ModelID: 9, Year: 2014, Style: 'Crossover', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 131313, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 475000000 },
      { ModelID: 10, Year: 2021, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 19900, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 539000000 },
      { ModelID: 11, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 22000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1750000000 },
      { ModelID: 12, Year: 2008, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 150000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 388000000 },
      { ModelID: 13, Year: 2024, Style: 'SUV', Condition: 'Xe mới', Origin: 'Nhập khẩu', Mileage: 0, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 879000000 },
      { ModelID: 14, Year: 2018, Style: 'Coupe', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 50000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1100000000 },
      { ModelID: 17, Year: 2015, Style: 'Bán Tải', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 80000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 560000000 },
      { ModelID: 18, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 45000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 870000000 },
      { ModelID: 19, Year: 2019, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 65000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 398000000 },
      { ModelID: 20, Year: 2023, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 45000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 840000000 },
      { ModelID: 21, Year: 2021, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 85000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1730000000 },
      { ModelID: 22, Year: 2019, Style: 'Bán tải', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 40000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 466000000 },
      { ModelID: 23, Year: 2013, Style: 'Van', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 100000, Gear: 'Số sàn', FuelType: 'Máy dầu', Price: 300000000 },
      { ModelID: 24, Year: 2014, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 100000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 295000000 },
      { ModelID: 28, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 58000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 249000000 },
      { ModelID: 32, Year: 2012, Style: 'Convertible', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 88950, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 980000000 },
      { ModelID: 33, Year: 2022, Style: 'Bán tải', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 50000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 825000000 },
      { ModelID: 34, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 40000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 365000000 },
      { ModelID: 35, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 69000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 435000000 },
      { ModelID: 36, Year: 2019, Style: 'Crossover', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 70000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 715000000 },
      { ModelID: 37, Year: 2018, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 92000, Gear: 'Số sàn', FuelType: 'Máy dầu', Price: 599000000 },
      { ModelID: 38, Year: 2013, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 110000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 390000000 },
      { ModelID: 41, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 60000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 440000000 },
      { ModelID: 42, Year: 2011, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 130000, Gear: 'Số sàn', FuelType: 'Máy xăng', Price: 209000000 },
      { ModelID: 43, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 40000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 565000000 },
      { ModelID: 44, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 80000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 415000000 },
      { ModelID: 45, Year: 2009, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 145000, Gear: 'Số sàn', FuelType: 'Máy xăng', Price: 139000000 },
      { ModelID: 46, Year: 2019, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 65000, Gear: 'Số sàn', FuelType: 'Máy xăng', Price: 245000000 },
      { ModelID: 47, Year: 2015, Style: 'Coupe', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 8000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 345000000 },
      { ModelID: 48, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 50000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 540000000 },
      { ModelID: 49, Year: 2017, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 65000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 265000000 },
      { ModelID: 50, Year: 2021, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 60000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 750000000 },
      { ModelID: 51, Year: 2019, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 70000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 509000000 },
      { ModelID: 52, Year: 2022, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 28000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 566000000 },
      { ModelID: 53, Year: 2018, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 66000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 775000000 },
      { ModelID: 54, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 41000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 655000000 },
      { ModelID: 55, Year: 2022, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 20000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1399000000 },
      { ModelID: 56, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 20000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 400000000 },
      { ModelID: 58, Year: 2023, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 800, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1390000000 },
      { ModelID: 60, Year: 2021, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 63000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 820000000 },
      { ModelID: 64, Year: 2016, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 70000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 650000000 },
      { ModelID: 65, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 31700, Gear: 'Số tự động', FuelType: 'Hybrid', Price: 1659000000 },
      { ModelID: 66, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 64000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1130000000 },
      { ModelID: 67, Year: 2019, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 59000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 2699000000 },
      { ModelID: 68, Year: 2018, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 83000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1380000000 },
      { ModelID: 69, Year: 2015, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 136000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 759000000 },
      { ModelID: 70, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 20000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1990000000 },
      { ModelID: 71, Year: 2018, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 68000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1179000000 },
      { ModelID: 72, Year: 2021, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 55000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 3199000000 },
      { ModelID: 73, Year: 2015, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 75000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 569000000 },
      { ModelID: 74, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 40000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1150000000 },
      { ModelID: 75, Year: 2024, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 22000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1599000000 },
      { ModelID: 76, Year: 2018, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 63000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 2280000000 },
      { ModelID: 77, Year: 2021, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 61000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1460000000 },
      { ModelID: 78, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 10000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 3099000000 },
      { ModelID: 79, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 30000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 4099000000 },
      { ModelID: 80, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 24000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 3799000000 },
      { ModelID: 81, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 23000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 2999000000 },
      { ModelID: 82, Year: 2016, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 56789, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 4699000000 },
      { ModelID: 83, Year: 2008, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 90000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 770000000 },
      { ModelID: 85, Year: 2019, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 46000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1719000000 },
      { ModelID: 86, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 60000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 2230000000 },
      { ModelID: 87, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 16000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 2630000000 },
      { ModelID: 88, Year: 2015, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 70000, Gear: 'Số sàn', FuelType: 'Máy xăng', Price: 1150000000 },
      { ModelID: 89, Year: 2022, Style: 'Sport Car', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 8000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 4479000000 },
      { ModelID: 90, Year: 2017, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 38000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1720000000 },
      { ModelID: 91, Year: 2017, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 71000, Gear: 'Số hỗn hợp', FuelType: 'Máy xăng', Price: 3599000000 },
      { ModelID: 92, Year: 2022, Style: 'Sport Car', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 8000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 9499000000 },
      { ModelID: 93, Year: 2019, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 48000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 3699000000 },
      { ModelID: 94, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 27000, Gear: 'Số tự động', FuelType: 'Điện', Price: 5000000000 },
      { ModelID: 96, Year: 2009, Style: 'Covertible', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 70000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1200000000 },
      { ModelID: 97, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 60000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 560000000 },
      { ModelID: 98, Year: 2020, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 50000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 718000000 },
      { ModelID: 99, Year: 2019, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 30000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 319000000 },
      { ModelID: 100, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 79000, Gear: 'Số tự động', FuelType: 'Điện', Price: 480000000 },
      { ModelID: 101, Year: 2022, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 20000, Gear: 'Số tự động', FuelType: 'Điện', Price: 850000000 },
      { ModelID: 102, Year: 2023, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 19000, Gear: 'Số tự động', FuelType: 'Điện', Price: 1140000000 },
      { ModelID: 104, Year: 2024, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 700, Gear: 'Số tự động', FuelType: 'Điện', Price: 255000000 },
      { ModelID: 105, Year: 2019, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 46000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 475000000 },
      { ModelID: 106, Year: 2018, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 110000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 625000000 },
      { ModelID: 107, Year: 2020, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 9000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 760000000 },
      { ModelID: 108, Year: 2015, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 90000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 328000000 },
      { ModelID: 109, Year: 2018, Style: 'Bán tải', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 110000, Gear: 'Số tự động', FuelType: 'Máy dầu', Price: 425000000 },
      { ModelID: 110, Year: 2024, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 20000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1075000000 },
      { ModelID: 111, Year: 2022, Style: 'Crossover', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 18000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 525000000 },
      { ModelID: 112, Year: 2022, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 1, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 690000000 },
      { ModelID: 113, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 13, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 470000000 },
      { ModelID: 114, Year: 2021, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 78000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 655000000 },
      { ModelID: 115, Year: 2014, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 120000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 470000000 },
      { ModelID: 116, Year: 2008, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 102000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 375000000 },
      { ModelID: 117, Year: 2019, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 48000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 345000000 },
      { ModelID: 118, Year: 2023, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Trong nước', Mileage: 31000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 675000000 },
      { ModelID: 119, Year: 2019, Style: 'Hatchback', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 147000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 380000000 },
      { ModelID: 120, Year: 2016, Style: 'MPV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 98000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 790000000 },
      { ModelID: 121, Year: 2013, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 78000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 450000000 },
      { ModelID: 122, Year: 2013, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 100000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 550000000 },
      { ModelID: 123, Year: 2017, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 89000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1179000000 },
      { ModelID: 124, Year: 2022, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 22000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 1699000000 },
      { ModelID: 125, Year: 2011, Style: 'Sedan', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 55000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 999000000 },
      { ModelID: 126, Year: 2013, Style: 'SUV', Condition: 'Xe cũ', Origin: 'Nhập khẩu', Mileage: 79000, Gear: 'Số tự động', FuelType: 'Máy xăng', Price: 748000000 },
  ]);

  // Thêm dữ liệu vào bảng CarImages: chua lam
  // await knex('CarImages').insert([
  //     { CarID: 1, ImageURL: 'https://example.com/corolla.jpg' },
  //     { CarID: 2, ImageURL: 'https://example.com/mustang.jpg' },
  // ]);

  // Thêm dữ liệu vào bảng Listings
  await knex('Listings').insert([
      { UserID: 1, CarID: 1, Status: 'available', Description: 'Vios E CVT 2022', DatePosted: new Date() },
      { UserID: 2, CarID: 2, Status: 'available', Description: 'Toyota Innova 2. 0V Full Options 2019 siêu lướt', DatePosted: new Date() },
  ]);

  // Thêm dữ liệu vào bảng Favorites
  await knex('Favorites').insert([
      { UserID: 1, ListingID: 1 },
      { UserID: 2, ListingID: 2 },
  ]);
};
